# docker-compose.yml #
version: "3.4"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    environment: 
      APP_PORT: ${APP_PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PASSWORD_HASH_ROUNDS: ${PASSWORD_HASH_ROUNDS}
      NODE_ENV: ${NODE_ENV}
    command: npm test
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "bambee-tasks-db:/data/db"
volumes:
  bambee-tasks-db: